apiVersion: apps/v1
kind: Deployment
metadata:
  name: ianus
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ianus
  template:
    metadata:
      labels:
        app: ianus
    spec:
      containers:
        - image: vuezee/ianus
          name: ianus
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
      restartPolicy: Always
